"""followers

Revision ID: 33408b9a18e8
Revises: b24b69f4cffb
Create Date: 2020-07-31 00:42:05.665238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33408b9a18e8'
down_revision = 'b24b69f4cffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
